title:            MY NOTEPAD
description:      "640K ought to be enough for anybody. - Bill Gates, 1981"
logo:             logo.png
disqus_shortname: katieball-notepad
share:            true
dropcap:          true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:              /notepad

# Emoji please
gems:
  - jemoji

# Owner/author information
owner:
  name:           Katie Ball
  avatar:         http://test.roachhaus.com/cv/img/katie11.png
  email:          katie@roachhd.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Coded with &#10084; in Melbourne.
# Social networking links used in footer. Update and remove as you like.
  twitter:        mektball
  facebook:       roachhd 
  github:         roachhd      
  instagram:      RoachHD
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-googled-7
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about
  - title: Tags
    url: /tags

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Melbourne
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://roachhd.github.io/notepad'
  relativeLinks: 'http://roachhd.github.io/notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Game-Development"
              value: game-development 
            - name: "Design"
              value: Design
            - name: "Geek"
              value: geek
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: Web-development
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "dev gamedev design PhotoShop grunt node Jekyll github azure apps games websites"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Use the following plug-ins
gems:
  - jekyll-sitemap 
# Create a sitemap using the official Jekyll sitemap gems
